const List<String> teamNames = [
  'Al Ahly',
  'Al Hilal',
  'Al Nassr',
  'Arsenal',
  'Aston Villa',
  'Atletico Madrid',
  'Barcelona',
  'Bayern Munich',
  'Benfica',
  'Borussia Dortmund',
  'Bournemouth',
  'Brentford',
  'Brighton & Hove Albion',
  'Burnley',
  'Celtic',
  'Chelsea',
  'Crystal Palace',
  'Derby County',
  'Everton',
  'Flamengo',
  'Fluminense',
  'Fulham',
  'Galatasaray',
  'Inter Milan',
  'Juventus',
  'Kerala Blasters',
  'Leeds United',
  'Leicester City',
  'Liverpool',
  'Luton Town',
  'Lyon',
  'Manchester City',
  'Manchester United',
  'Marseille',
  'Milan',
  'Monaco',
  'Napoli',
  'Newcastle United',
  'Nottingham Forest',
  'Olympiacos',
  'Paris Saint-Germain',
  'Porto',
  'PSV Eindhoven',
  'Rangers',
  'Real Madrid',
  'Roma',
  'River Plate',
  'Sheffield United',
  'Southampton',
  'Sporting CP',
  'Stoke City',
  'Sunderland',
  'Swansea City',
  'Tottenham Hotspur',
  'West Ham United',
  'Wolverhampton Wanderers',
  'Ajax',
  'Feyenoord',
  'Boca Juniors',
  'Corinthians',
  'Santos',
  'Sao Paulo',
  'Palmeiras',
  'Gremio',
  'Internacional',
  'Cruzeiro',
  'Atletico Mineiro',
  'Vasco da Gama',
  'Botafogo',
  'Argentinos Juniors',
  'Independiente',
  'Racing Club',
  'San Lorenzo',
  'Velez Sarsfield',
  'Colo-Colo',
  'Universidad de Chile',
  'Nacional',
  'Penarol',
  'Barcelona SC',
  'LDU Quito',
  'Emelec',
  'Club America',
  'Chivas Guadalajara',
  'Cruz Azul',
  'Pumas UNAM',
  'Tigres UANL',
  'Monterrey',
  'Leon',
  'Santos Laguna',
  'Toluca',
  'DC United',
  'LA Galaxy',
  'Seattle Sounders',
  'New York Red Bulls',
  'Atlanta United',
  'Inter Miami',
  'Portland Timbers',
  'Toronto FC',
  'Vancouver Whitecaps',
  'LAFC',
  'Philadelphia Union',
  'Columbus Crew',
  'Sporting Kansas City',
  'Real Salt Lake',
  'Chicago Fire',
  'Shanghai Port',
  'Guangzhou FC',
  'Shandong Taishan',
  'Beijing Guoan',
  'Urawa Red Diamonds',
  'Kashima Antlers',
  'Kawasaki Frontale',
  'Yokohama F Marinos',
  'Jeonbuk Hyundai Motors',
  'Ulsan Hyundai',
  'Pohang Steelers',
  'Sydney FC',
  'Melbourne Victory',
  'Western Sydney Wanderers',
  'Brisbane Roar',
  'Kaizer Chiefs',
  'Orlando Pirates',
  'Mamelodi Sundowns',
  'TP Mazembe',
  'ES Tunis',
  'Zamalek',
  'Raja Casablanca',
  'Wydad Casablanca',
  'Asante Kotoko',
  'Hearts of Oak',
  'Enyimba',
  'Rangers International',
  'Fenerbahce',
  'Besiktas',
  'Trabzonspor',
  'Basaksehir',
  'Shakhtar Donetsk',
  'Dynamo Kyiv',
  'Spartak Moscow',
  'CSKA Moscow',
  'Zenit Saint Petersburg',
  'Lokomotiv Moscow',
  'Red Star Belgrade',
  'Partizan Belgrade',
  'Dinamo Zagreb',
  'Hajduk Split',
  'Slavia Prague',
  'Sparta Prague',
  'Legia Warsaw',
  'Wisla Krakow',
  'Anderlecht',
  'Club Brugge',
  'Racing Genk',
  'Standard Liege',
  'Basel',
  'Young Boys',
  'FC Zurich',
  'Salzburg',
  'Rapid Vienna',
  'Austria Vienna',
  'Copenhagen',
  'Midtjylland',
  'Brondby',
  'Malmo FF',
  'AIK',
  'Djurgarden',
  'Rosenborg',
  'Molde',
  'Bodo/Glimt',
  'PAOK',
  'AEK Athens',
  'Panathinaikos',
];
